export const INITIALIZE_GAME = 'INITIALIZE GAME';
export const CREATE_ORDER = 'CREATE ORDER';
export const SHOW_ORDER_ALERT = 'SHOW ORDER ALERT';
export const HIDE_ORDER_ALERT = 'HIDE ORDER ALERT';
// Auth
export const REQUEST_TOKEN = 'REQUEST TOKEN';
export const RECEIVE_TOKEN = 'RECEIVE TOKEN';
export const REQUEST_CURRENT_USER = 'REQUEST_CURRENT_USER';
export const RECEIVE_CURRENT_USER = 'RECEIVE_CURRENT_USER';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const RESET_ERROR = 'RESET_ERROR';
export const NO_TOKEN = 'NO_TOKEN';
