export const CREATE_ORDER = 'CREATE ORDER';
export const SHOW_ORDER_ALERT = 'SHOW ORDER ALERT';
export const HIDE_ORDER_ALERT = 'HIDE ORDER ALERT';
// Auth
export const REQUEST_TOKEN = 'REQUEST TOKEN';
export const RECEIVE_TOKEN = 'RECEIVE TOKEN';
export const REQUEST_CURRENT_USER = 'REQUEST CURRENT USER';
export const RECEIVE_CURRENT_USER = 'RECEIVE CURRENT USER';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION ERROR';
export const RESET_ERROR = 'RESET ERROR';
export const NO_TOKEN = 'NO_TOKEN';
// Game
export const REQUEST_GAME_CREATION = 'REQUEST GAME CREATION';
export const GAME_CREATION_ERROR = 'GAME CREATION ERROR';
export const REQUEST_GAME_DATA = 'REQUEST GAME DATA';
export const RECEIVE_GAME_DATA = 'RECEIVE GAME DATA';
export const GAME_DATA_ERROR = 'GAME DATA ERROR';
export const REQUEST_ORDERS_SUBMISSION = 'REQUEST ORDERS SUBMISSION';
export const ORDERS_SUBMISSION_ERROR = 'ORDERS SUBMISSION ERROR';
